#                                                                                                             
#                                                                                                             
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                                                                                                             
#                                              ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                            

# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 

[window]
opacity=0.3

[colors]
transparent_background_colors = false

[colors.primary]
background = "#081B24"
foreground = "#D6E7E8"

[colors.normal]
black   = "#081B24"
red     = "#AA4C37"
green   = "#13738C"
yellow  = "#CB6551"
blue    = "#158CA3"
magenta = "#B88C90"
cyan    = "#24C4D3"
white   = "#D6E7E8"

[colors.bright]
black   = "#293A44"
red     = "#E18A72"
green   = "#196075"
yellow  = "#F0B7A8"
blue    = "#F0F7F7"
magenta = "#D2A5A8"
cyan    = "#72E2EA"
white   = "#FFFFFF"

[colors.cursor]
text   = "#060708"
cursor = "#F0F7F7"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
