#                                                                                                             
#                                                                                                             
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                                                                                                             
#                                          ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                            


[colors-dark]
background=1b2d40
foreground=d6e2ee
alpha=0.3
alpha-mode=all
cursor=071018 f2fcff
selection-background=4d9ed3
selection-foreground=071018

regular0=1b2d40
regular1=4d86b0
regular2=5e95bc
regular3=6fa4c9
regular4=6fb8e3
regular5=8bc9eb
regular6=b4e4f6
regular7=d6e2ee

bright0=304860
bright1=73a6cb
bright2=86b7d8
bright3=9dcae5
bright4=f2fcff
bright5=b1d8ee
bright6=d1eef8
bright7=ffffff
