#                                                                                                             
#                                                                                                             
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                                                                                                             
#                                          ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                            #                                                                                                             

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 


# Background and foreground colors
background = #081B24
foreground = #D6E7E8
background-opacity = 0.3
# Standard colors
palette = 0=#081B24
palette = 1=#AA4C37
palette = 2=#13738C
palette = 3=#CB6551
palette = 4=#158CA3
palette = 5=#B88C90
palette = 6=#24C4D3
palette = 7=#D6E7E8

# Bright colors
palette = 8=#293A44
palette = 9=#E18A72
palette = 10=#196075
palette = 11=#F0B7A8
palette = 12=#F0F7F7
palette = 13=#D2A5A8
palette = 14=#72E2EA
palette = 15=#FFFFFF

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
