#                                                                                                             
#                                                                                                             
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#    @              @@           @@         @@  @@ @@@   @@@ @@  @@@@      @@@@ @@    @@@  @@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                                                                                                             
#                                          ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                        
# hyprland.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

$activeBorderColor = rgb(f2fcff)
$activeShadowColor = rgb(6fb8e3)
$inactiveBorderColor = rgba(30486099)
$inactiveShadowColor = rgba(30486077)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 14
    gaps_out = 28
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 6
    rounding_power = 7
    blur {
        enabled = true
        size = 2
        passes = 3
        noise = 0.05
      }
      shadow {
          enabled = true
          range = 16
          render_power = 4
          color = $activeShadowColor
          color_inactive = $inactiveShadowColor
        }
  }
#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
