#                                                                                                             
#                                                                                                             
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                                                                                                             
#                                          ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                        

# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #081B24
foreground            #D6E7E8
background_opacity 0.3
dynamic_background_opacity yes

# black
color0  #081B24
color8  #293A44

# red
color1  #AA4C37
color9  #E18A72

# green
color2  #13738C
color10 #196075

# yellow
color3  #CB6551
color11 #F0B7A8

# blue
color4  #158CA3
color12 #F0F7F7

# magenta
color5  #B88C90
color13 #D2A5A8

#cyan
color6  #24C4D3
color14 #72E2EA

#white
color7  #D6E7E8
color15 #FFFFFF

cursor_shape block
cursor_blink_interval 0.6 ease-in-out
cursor_stop_blinking_after 0

cursor_trail 8
cursor_trail_decay 0.08 0.25
cursor_trail_start_threshold 1
cursor_trail_color #F0F7F7
#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
